# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

before_build:
  # Avoid note about non-standard file/directory during R CMD check.
  - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"

build_script:
  - git config --global user.name "travis"
  - git config --global user.email "travis@example.org"
  - Rscript -e "install.packages('xgboost', repos=c('http://dmlc.ml/drat/', 'https://cran.cnr.berkeley.edu/'), type='source')"
  #- travis-tool.sh install_bioc BiocInstaller
  - Rscript -e "source('https://bioconductor.org/biocLite.R'); biocLite()"
  #- travis-tool.sh install_bioc sva genefilter
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_deps
  - travis-tool.sh github_package jimhester/covr

test_script:
  - travis-tool.sh run_tests
  # Review current working directory.
  - Rscript -e "print(getwd()); print(ls())"
  # Run devtools::check_revdep() if we're set the SL_CRAN environmental var
  # and this isn't a pull request.

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

on_success:
  - Rscript -e 'covr::codecov()'

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    _R_CHECK_FORCE_SUGGESTS_: 0
    R_ARCH: x64
    USE_RTOOLS: true ## to be able to use Remotes (i.e. packages from non-CRAN sources)

  matrix:
    - R_VERSION: release
    - R_VERSION: oldrel
    - R_VERSION: devel

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

cache:
  - C:\RLibrary
